/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.2-42-g5d7a2a13e6"
#endif /* AVUTIL_FFVERSION_H */
